services:
  geometry:
    container_name: "trial1"
    image: geometry
    ports:
      - "8080:80"
    volumes:
      - ./:/home/geometry
    env_file:
      - "./geometry.env"
    stdin_open: true
    tty: true
  z3:
    container_name: "EuclidZ3"
    image: euclidz3:v1
    volumes:
      - ./:/home/geometry
    stdin_open: true
    tty: true
    